export const GET_CACHE_REQUEST = 'GET_CACHE_REQUEST';
export const GET_CACHE_SUCCESS = 'GET_CACHE_SUCCESS';
export const GET_CACHE_FAILURE = 'GET_CACHE_FAILURE';
export const GET_CACHE_FROM_LOCAL = 'GET_CACHE_FROM_LOCAL';

export const GET_CACHE_USER_FUNCTION_LIST = 'ERPUSERCACHE.FUNCTION';

// lý do hủy giao hàng
export const CANCELDELIVERYREASON_VIEW = 'CANCELDELIVERYREASON_VIEW';
export const CANCELDELIVERYREASON_ADD = 'CANCELDELIVERYREASON_ADD';
export const CANCELDELIVERYREASON_UPDATE = 'CANCELDELIVERYREASON_UPDATE';
export const CANCELDELIVERYREASON_DELETE = 'CANCELDELIVERYREASON_DELETE';

// loại phương tiện vận chuyển
export const CARRIERTYPE_VIEW = 'CARRIERTYPE_VIEW';
export const CARRIERTYPE_ADD = 'CARRIERTYPE_ADD';
export const CARRIERTYPE_UPDATE = 'CARRIERTYPE_UPDATE';
export const CARRIERTYPE_DELETE = 'CARRIERTYPE_DELETE';

// loại giấy tờ tùy thân
export const IDDOCUMENTTYPE_VIEW = 'IDDOCUMENTTYPE_VIEW';
export const IDDOCUMENTTYPE_ADD = 'IDDOCUMENTTYPE_ADD';
export const IDDOCUMENTTYPE_UPDATE = 'IDDOCUMENTTYPE_UPDATE';
export const IDDOCUMENTTYPE_DELETE = 'IDDOCUMENTTYPE_DELETE';

// gói sản phẩm lắp đặt kèm theo
export const INSTALLBUNDLE_VIEW = 'INSTALLBUNDLE_VIEW';
export const INSTALLBUNDLE_ADD = 'INSTALLBUNDLE_ADD';
export const INSTALLBUNDLE_UPDATE = 'INSTALLBUNDLE_UPDATE';
export const INSTALLBUNDLE_DELETE = 'INSTALLBUNDLE_DELETE';

// nhóm sản phẩm cần vật tư lắp đặt
export const INSTALLMATERIAL_VIEW = 'INSTALLMATERIAL_VIEW';
export const INSTALLMATERIAL_ADD = 'INSTALLMATERIAL_ADD';
export const INSTALLMATERIAL_UPDATE = 'INSTALLMATERIAL_UPDATE';
export const INSTALLMATERIAL_DELETE = 'INSTALLMATERIAL_DELETE';

// loại đóng gói hàng hóa vận chuyển
export const PACKAGETYPE_VIEW = 'PACKAGETYPE_VIEW';
export const PACKAGETYPE_ADD = 'PACKAGETYPE_ADD';
export const PACKAGETYPE_UPDATE = 'PACKAGETYPE_UPDATE';
export const PACKAGETYPE_DELETE = 'PACKAGETYPE_DELETE';

// đối tác
export const PARTNER_VIEW = 'PARTNER_VIEW';
export const PARTNER_ADD = 'PARTNER_ADD';
export const PARTNER_UPDATE = 'PARTNER_UPDATE';
export const PARTNER_DELETE = 'PARTNER_DELETE';

// quyền nhà cung cấp
export const PARTNERPRIVILEDGE_VIEW = 'PARTNERPRIVILEDGE_VIEW';
export const PARTNERPRIVILEDGE_ADD = 'PARTNERPRIVILEDGE_ADD';
export const PARTNERPRIVILEDGE_UPDATE = 'PARTNERPRIVILEDGE_UPDATE';
export const PARTNERPRIVILEDGE_DELETE = 'PARTNERPRIVILEDGE_DELETE';

// nhóm quyền nhà cung cấp
export const PARTNERPRIVILEDGEGROUP_VIEW = 'PARTNERPRIVILEDGEGROUP_VIEW';
export const PARTNERPRIVILEDGEGROUP_ADD = 'PARTNERPRIVILEDGEGROUP_ADD';
export const PARTNERPRIVILEDGEGROUP_UPDATE = 'PARTNERPRIVILEDGEGROUP_UPDATE';
export const PARTNERPRIVILEDGEGROUP_DELETE = 'PARTNERPRIVILEDGEGROUP_DELETE';

// vai trò người dùng của nhà cung cấp
export const PARTNERROLE_VIEW = 'PARTNERROLE_VIEW';
export const PARTNERROLE_ADD = 'PARTNERROLE_ADD';
export const PARTNERROLE_UPDATE = 'PARTNERROLE_UPDATE';
export const PARTNERROLE_DELETE = 'PARTNERROLE_DELETE';

// người dùng của nhà cung cấp
export const PARTNERUSER_VIEW = 'PARTNERUSER_VIEW';
export const PARTNERUSER_ADD = 'PARTNERUSER_ADD';
export const PARTNERUSER_UPDATE = 'PARTNERUSER_UPDATE';
export const PARTNERUSER_DELETE = 'PARTNERUSER_DELETE';

// loại hợp đồng dịch vụ
export const SERVICEAGREEMENTTYPE_VIEW = 'SERVICEAGREEMENTTYPE_VIEW';
export const SERVICEAGREEMENTTYPE_ADD = 'SERVICEAGREEMENTTYPE_ADD';
export const SERVICEAGREEMENTTYPE_UPDATE = 'SERVICEAGREEMENTTYPE_UPDATE';
export const SERVICEAGREEMENTTYPE_DELETE = 'SERVICEAGREEMENTTYPE_DELETE';

// loại mùa dịch vụ
export const SERVICESEASONTYPE_VIEW = 'SERVICESEASONTYPE_VIEW';
export const SERVICESEASONTYPE_ADD = 'SERVICESEASONTYPE_ADD';
export const SERVICESEASONTYPE_UPDATE = 'SERVICESEASONTYPE_UPDATE';
export const SERVICESEASONTYPE_DELETE = 'SERVICESEASONTYPE_DELETE';

// loại dịch vụ
export const SERVICETYPE_VIEW = 'SERVICETYPE_VIEW';
export const SERVICETYPE_ADD = 'SERVICETYPE_ADD';
export const SERVICETYPE_UPDATE = 'SERVICETYPE_UPDATE';
export const SERVICETYPE_DELETE = 'SERVICETYPE_DELETE';

// phương thức thanh toán chi phí vận chuyển
export const SHIPMENTFEEPAYMENTMETHOD_VIEW = 'SHIPMENTFEEPAYMENTMETHOD_VIEW';
export const SHIPMENTFEEPAYMENTMETHOD_ADD = 'SHIPMENTFEEPAYMENTMETHOD_ADD';
export const SHIPMENTFEEPAYMENTMETHOD_UPDATE = 'SHIPMENTFEEPAYMENTMETHOD_UPDATE';
export const SHIPMENTFEEPAYMENTMETHOD_DELETE = 'SHIPMENTFEEPAYMENTMETHOD_DELETE';

// loại phí vận chuyển
export const SHIPMENTFEETYPE_VIEW = 'SHIPMENTFEETYPE_VIEW';
export const SHIPMENTFEETYPE_ADD = 'SHIPMENTFEETYPE_ADD';
export const SHIPMENTFEETYPE_UPDATE = 'SHIPMENTFEETYPE_UPDATE';
export const SHIPMENTFEETYPE_DELETE = 'SHIPMENTFEETYPE_DELETE';

// loại hàng hóa vận chuyển
export const SHIPMENTGOODSTYPE_VIEW = 'SHIPMENTGOODSTYPE_VIEW';
export const SHIPMENTGOODSTYPE_ADD = 'SHIPMENTGOODSTYPE_ADD';
export const SHIPMENTGOODSTYPE_UPDATE = 'SHIPMENTGOODSTYPE_UPDATE';
export const SHIPMENTGOODSTYPE_DELETE = 'SHIPMENTGOODSTYPE_DELETE';

//nhóm trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUSGROUP_VIEW = 'SHIPMENTORDERSTATUSGROUP_VIEW';
export const SHIPMENTORDERSTATUSGROUP_ADD = 'SHIPMENTORDERSTATUSGROUP_ADD';
export const SHIPMENTORDERSTATUSGROUP_UPDATE = 'SHIPMENTORDERSTATUSGROUP_UPDATE';
export const SHIPMENTORDERSTATUSGROUP_DELETE = 'SHIPMENTORDERSTATUSGROUP_DELETE';

// trạng thái yêu cầu vận chuyển
export const SHIPMENTORDERSTATUS_VIEW = 'SHIPMENTORDERSTATUS_VIEW';
export const SHIPMENTORDERSTATUS_ADD = 'SHIPMENTORDERSTATUS_ADD';
export const SHIPMENTORDERSTATUS_UPDATE = 'SHIPMENTORDERSTATUS_UPDATE';
export const SHIPMENTORDERSTATUS_DELETE = 'SHIPMENTORDERSTATUS_DELETE';

// bước xử lý yêu cầu vận chuyển
export const SHIPMENTORDERSTEP_VIEW = 'SHIPMENTORDERSTEP_VIEW';
export const SHIPMENTORDERSTEP_ADD = 'SHIPMENTORDERSTEP_ADD';
export const SHIPMENTORDERSTEP_UPDATE = 'SHIPMENTORDERSTEP_UPDATE';
export const SHIPMENTORDERSTEP_DELETE = 'SHIPMENTORDERSTEP_DELETE';

// loại dịch vụ vận chuyển
export const SHIPMENTSERVICETYPE_VIEW = 'SHIPMENTSERVICETYPE_VIEW';
export const SHIPMENTSERVICETYPE_ADD = 'SHIPMENTSERVICETYPE_ADD';
export const SHIPMENTSERVICETYPE_UPDATE = 'SHIPMENTSERVICETYPE_UPDATE';
export const SHIPMENTSERVICETYPE_DELETE = 'SHIPMENTSERVICETYPE_DELETE';

// loại đối tác
export const PARTNERTYPE_VIEW = 'PARTNERTYPE_VIEW';
export const PARTNERTYPE_ADD = 'PARTNERTYPE_ADD';
export const PARTNERTYPE_UPDATE = 'PARTNERTYPE_UPDATE';
export const PARTNERTYPE_DELETE = 'PARTNERTYPE_DELETE';

// loại yêu cầu vận chuyển
export const SHIPMENTORDERTYPE_VIEW = 'SHIPMENTORDERTYPE_VIEW';
export const SHIPMENTORDERTYPE_ADD = 'SHIPMENTORDERTYPE_ADD';
export const SHIPMENTORDERTYPE_UPDATE = 'SHIPMENTORDERTYPE_UPDATE';
export const SHIPMENTORDERTYPE_DELETE = 'SHIPMENTORDERTYPE_DELETE';

// yêu cầu vận chuyển
export const SHIPMENTORDER_VIEW = 'SHIPMENTORDER_VIEW';
export const SHIPMENTORDER_ADD = 'SHIPMENTORDER_ADD';
export const SHIPMENTORDER_UPDATE = 'SHIPMENTORDER_UPDATE';
export const SHIPMENTORDER_DELETE = 'SHIPMENTORDER_DELETE';
export const SHIPMENTORDER_EXPECTEDDELIVERYDATE = 'SHIPMENTORDER_EXPECTEDDELIVERYDATE';



// hợp đồng dịch vụ
export const SERVICEAGREEMENT_VIEW = 'SERVICEAGREEMENT_VIEW';
export const SERVICEAGREEMENT_ADD = 'SERVICEAGREEMENT_ADD';
export const SERVICEAGREEMENT_UPDATE = 'SERVICEAGREEMENT_UPDATE';
export const SERVICEAGREEMENT_DELETE = 'SERVICEAGREEMENT_DELETE';

// Phụ lục biểu phí
export const FEEAPPENDIX_VIEW = 'FEEAPPENDIX_VIEW';
export const FEEAPPENDIX_ADD = 'FEEAPPENDIX_ADD';
export const FEEAPPENDIX_UPDATE = 'FEEAPPENDIX_UPDATE';
export const FEEAPPENDIX_DELETE = 'FEEAPPENDIX_DELETE';

// Phụ lục biểu phí
export const ABILITI_VIEW = 'ABILITI_VIEW';
export const ABILITI_ADD = 'ABILITI_ADD';
export const ABILITI_UPDATE = 'ABILITI_UPDATE';
export const ABILITI_DELETE = 'ABILITI_DELETE';

// Chi tiết phụ lục biểu phí
export const FEEAPPENDIXDETAIL_VIEW = 'FEEAPPENDIXDETAIL_VIEW';
export const FEEAPPENDIXDETAIL_ADD = 'FEEAPPENDIXDETAIL_ADD';
export const FEEAPPENDIXDETAIL_UPDATE = 'FEEAPPENDIXDETAIL_UPDATE';
export const FEEAPPENDIXDETAIL_DELETE = 'FEEAPPENDIXDETAIL_DELETE';

// Định nghĩa kho điều phối giao hàng
export const COORDINATORSTORE_VIEW = 'COORDINATORSTORE_VIEW';
export const COORDINATORSTORE_ADD = 'COORDINATORSTORE_ADD';
export const COORDINATORSTORE_UPDATE = 'COORDINATORSTORE_UPDATE';
export const COORDINATORSTORE_DELETE = 'COORDINATORSTORE_DELETE';

// thông tin giao dịch với đối tác
export const PARTNERTRANSACTION_VIEW = 'PARTNERTRANSACTION_VIEW';

// nhật ký gọi api
export const APICALLLOG_VIEW = 'APICALLLOG_VIEW';

// yêu cầu tạm ứng
export const ADVANCEREQUEST_VIEW = 'ADVANCEREQUEST_VIEW';


// kỹ năng
export const SKILL_VIEW = 'SKILL_VIEW';
export const SKILL_ADD = 'SKILL_ADD';
export const SKILL_UPDATE = 'SKILL_UPDATE';
export const SKILL_DELETE = 'SKILL_DELETE';

// danh mục kỹ năng
export const SKILLCATEGORY_VIEW = 'SKILLCATEGORY_VIEW';
export const SKILLCATEGORY_ADD = 'SKILLCATEGORY_ADD';
export const SKILLCATEGORY_UPDATE = 'SKILLCATEGORY_UPDATE';
export const SKILLCATEGORY_DELETE = 'SKILLCATEGORY_DELETE';

// cấp bậc kỹ năng
export const SKILLRANK_VIEW = 'SKILLRANK_VIEW';
export const SKILLRANK_ADD = 'SKILLRANK_ADD';
export const SKILLRANK_UPDATE = 'SKILLRANK_UPDATE';
export const SKILLRANK_DELETE = 'SKILLRANK_DELETE';

// Danh sách xe
export const VEHICLE_VIEW = 'VEHICLE_VIEW';
export const VEHICLE_ADD = 'VEHICLE_ADD';
export const VEHICLE_UPDATE = 'VEHICLE_UPDATE';
export const VEHICLE_DELETE = 'VEHICLE_DELETE';

// Ca làm việc
export const WORKINGSHIFT_VIEW = 'WORKINGSHIFT_VIEW';
export const WORKINGSHIFT_ADD = 'WORKINGSHIFT_ADD';
export const WORKINGSHIFT_UPDATE = 'WORKINGSHIFT_UPDATE';
export const WORKINGSHIFT_DELETE = 'WORKINGSHIFT_DELETE';

// Phân ca làm việc của nhân viên
export const WORKINGPLAN_VIEW = 'WORKINGPLAN_VIEW';
export const WORKINGPLAN_ADD = 'WORKINGPLAN_ADD';
export const WORKINGPLAN_UPDATE = 'WORKINGPLAN_UPDATE';
export const WORKINGPLAN_DELETE = 'WORKINGPLAN_DELETE';

// loại khu vực
export const AREATYPE_VIEW = 'AREATYPE_VIEW';
export const AREATYPE_ADD = 'AREATYPE_ADD';
export const AREATYPE_UPDATE = 'AREATYPE_UPDATE';
export const AREATYPE_DELETE = 'AREATYPE_DELETE';

// khu vực
export const AREA_VIEW = 'AREA_VIEW';
export const AREA_ADD = 'AREA_ADD';
export const AREA_UPDATE = 'AREA_UPDATE';
export const AREA_DELETE = 'AREA_DELETE';

// kỹ năng của nhân viên
export const USERSKILL_VIEW = 'USERSKILL_VIEW';
export const USERSKILL_ADD = 'USERSKILL_ADD';
export const USERSKILL_UPDATE = 'USERSKILL_UPDATE';
export const USERSKILL_DELETE = 'USERSKILL_DELETE';

// Nhóm vật tư lắp đặt
export const MATERIALGROUP_VIEW = 'MATERIALGROUP_VIEW';
export const MATERIALGROUP_ADD = 'MATERIALGROUP_ADD';
export const MATERIALGROUP_UPDATE = 'MATERIALGROUP_UPDATE';
export const MATERIALGROUP_DELETE = 'MATERIALGROUP_DELETE';


// Nhóm danh sách tiền phải trả cho nhà cung cấp dịch vụ theo ngày
export const PARTNERPAYABLE_VIEW = 'PARTNERPAYABLE_VIEW';
export const PARTNERPAYABLE_ADD = 'PARTNERPAYABLE_ADD';
export const PARTNERPAYABLE_UPDATE = 'PARTNERPAYABLE_UPDATE';
export const PARTNERPAYABLE_DELETE = 'PARTNERPAYABLE_DELETE';

// Nhóm danh sách chi tiết tiền phải trả cho nhà cung cấp dịch vụ
export const PARTNERPAYABLEDETAIL_VIEW = 'PARTNERPAYABLEDETAIL_VIEW';
export const PARTNERPAYABLEDETAIL_ADD = 'PARTNERPAYABLEDETAIL_ADD';
export const PARTNERPAYABLEDETAIL_UPDATE = 'PARTNERPAYABLEDETAIL_UPDATE';
export const PARTNERPAYABLEDETAIL_DELETE = 'PARTNERPAYABLEDETAIL_DELETE';


// Loại giới hạn
export const LIMITTYPE_VIEW = 'LIMITTYPE_VIEW';
export const LIMITTYPE_ADD = 'LIMITTYPE_ADD';
export const LIMITTYPE_UPDATE = 'LIMITTYPE_UPDATE';
export const LIMITTYPE_DELETE = 'LIMITTYPE_DELETE';

// Bảng khai báo giới hạn theo người dùng
export const USER_LIMIT_VIEW = 'USER_LIMIT_VIEW';
export const USER_LIMIT_ADD = 'USER_LIMIT_ADD';
export const USER_LIMIT_UPDATE = 'USER_LIMIT_UPDATE';
export const USER_LIMIT_DELETE = 'USER_LIMIT_DELETE';

//Loại yêu cầu tạm ứng
export const ADVANCEREQUESTTYPE_VIEW = 'ADVANCEREQUESTTYPE_VIEW';
export const ADVANCEREQUESTTYPE_ADD = 'ADVANCEREQUESTTYPE_ADD';
export const ADVANCEREQUESTTYPE_UPDATE = 'ADVANCEREQUESTTYPE_UPDATE';
export const ADVANCEREQUESTTYPE_DELETE = 'ADVANCEREQUESTTYPE_DELETE';

//Loại yêu cầu hủy vật tư
export const DESTROYREQUESTTYPE_VIEW = 'DESTROYREQUESTTYPE_VIEW';
export const DESTROYREQUESTTYPE_ADD = 'DESTROYREQUESTTYPE_ADD';
export const DESTROYREQUESTTYPE_UPDATE = 'DESTROYREQUESTTYPE_UPDATE';
export const DESTROYREQUESTTYPE_DELETE = 'DESTROYREQUESTTYPE_DELETE';

//Loại yêu cầu kiểm kê
export const INVENTORYREQUESTTYPE_VIEW = 'INVENTORYREQUESTTYPE_VIEW';
export const INVENTORYREQUESTTYPE_ADD = 'INVENTORYREQUESTTYPE_ADD';
export const INVENTORYREQUESTTYPE_UPDATE = 'INVENTORYREQUESTTYPE_UPDATE';
export const INVENTORYREQUESTTYPE_DELETE = 'INVENTORYREQUESTTYPE_DELETE';

//Yêu cầu hủy vật tư
export const DESTROYREQUEST_VIEW = 'DESTROYREQUEST_VIEW';
export const DESTROYREQUEST_ADD = 'DESTROYREQUEST_ADD';
export const DESTROYREQUEST_UPDATE = 'DESTROYREQUEST_UPDATE';
export const DESTROYREQUEST_DELETE = 'DESTROYREQUEST_DELETE';

//Yêu cầu kiểm kê
export const INVENTORYREQUEST_VIEW = 'INVENTORYREQUEST_VIEW';
export const INVENTORYREQUEST_ADD = 'INVENTORYREQUEST_ADD';
export const INVENTORYREQUEST_UPDATE = 'INVENTORYREQUEST_UPDATE';
export const INVENTORYREQUEST_DELETE = 'INVENTORYREQUEST_DELETE';


//Loại thưởng
export const REWARDTYPE_VIEW = 'REWARDTYPE_VIEW';
export const REWARDTYPE_ADD = 'REWARDTYPE_ADD';
export const REWARDTYPE_UPDATE = 'REWARDTYPE_UPDATE';
export const REWARDTYPE_DELETE = 'REWARDTYPE_DELETE';

//Loại đơn giá thưởng
export const REWARDPRICETYPE_VIEW = 'REWARDPRICETYPE_VIEW';
export const REWARDPRICETYPE_ADD = 'REWARDPRICETYPE_ADD';
export const REWARDPRICETYPE_UPDATE = 'REWARDPRICETYPE_UPDATE';
export const REWARDPRICETYPE_DELETE = 'REWARDPRICETYPE_DELETE';


//Vị trí thưởng
export const REWARDPOSITION_VIEW = 'REWARDPOSITION_VIEW';
export const REWARDPOSITION_ADD = 'REWARDPOSITION_ADD';
export const REWARDPOSITION_UPDATE = 'REWARDPOSITION_UPDATE';
export const REWARDPOSITION_DELETE = 'REWARDPOSITION_DELETE';

//Loại thưởng của một vị trí thưởng
export const REWARDPOSITION_REWARDTYPE_VIEW = 'REWARDPOSITION_REWARDTYPE_VIEW';
export const REWARDPOSITION_REWARDTYPE_ADD = 'REWARDPOSITION_REWARDTYPE_ADD';
export const REWARDPOSITION_REWARDTYPE_UPDATE = 'REWARDPOSITION_REWARDTYPE_UPDATE';
export const REWARDPOSITION_REWARDTYPE_DELETE = 'REWARDPOSITION_REWARDTYPE_DELETE';

//Vị trí thưởng của 1 nhân viên
export const USER_REWARDPOSITION_VIEW = 'USER_REWARDPOSITION_VIEW';
export const USER_REWARDPOSITION_ADD = 'USER_REWARDPOSITION_ADD';
export const USER_REWARDPOSITION_UPDATE = 'USER_REWARDPOSITION_UPDATE';
export const USER_REWARDPOSITION_DELETE = 'USER_REWARDPOSITION_DELETE';


//kho thưởng của nhân viên quản lý
export const USER_REWARD_STORE_VIEW = 'USER_REWARD_STORE_VIEW';
export const USER_REWARD_STORE_ADD = 'USER_REWARD_STORE_ADD';
export const USER_REWARD_STORE_UPDATE = 'USER_REWARD_STORE_UPDATE';
export const USER_REWARD_STORE_DELETE = 'USER_REWARD_STORE_DELETE';

// bảng giá nhiên liệu
export const FUELPRICE_VIEW = 'FUELPRICE_VIEW';
export const FUELPRICE_ADD = 'FUELPRICE_ADD';
export const FUELPRICE_UPDATE = 'FUELPRICE_UPDATE';
export const FUELPRICE_DELETE = 'FUELPRICE_DELETE';

//Bảng đơn giá thưởng giao hàng và lắp đặt

export const REWARDPRICETABLE_VIEW = 'REWARDPRICETABLE_VIEW';
export const REWARDPRICETABLE_ADD = 'REWARDPRICETABLE_ADD';
export const REWARDPRICETABLE_UPDATE = 'REWARDPRICETABLE_UPDATE';
export const REWARDPRICETABLE_DELETE = 'REWARDPRICETABLE_DELETE';

//Bảng đơn giá thưởng giao hàng và lắp đặt

export const REWARDPRICETABLEDETAIL_VIEW = 'REWARDPRICETABLEDETAIL_VIEW';
export const REWARDPRICETABLEDETAIL_ADD = 'REWARDPRICETABLEDETAIL_ADD';
export const REWARDPRICETABLEDETAIL_UPDATE = 'REWARDPRICETABLEDETAIL_UPDATE';
export const REWARDPRICETABLEDETAIL_DELETE = 'REWARDPRICETABLEDETAIL_DELETE';


//Danh sách tập tin đính kèm yêu cầu hủy vật tư

export const DESTROYREQUEST_ATTACHMENT_VIEW = 'DESTROYREQUEST_ATTACHMENT_VIEW';
export const DESTROYREQUEST_ATTACHMENT_ADD = 'DESTROYREQUEST_ATTACHMENT_ADD';
export const DESTROYREQUEST_ATTACHMENT_UPDATE = 'DESTROYREQUEST_ATTACHMENT_UPDATE';
export const DESTROYREQUEST_ATTACHMENT_DELETE = 'DESTROYREQUEST_ATTACHMENT_DELETE';

//Danh sách bình luận của một yêu cầu hủy vật tư

export const DESTROYREQUEST_COMMENT_VIEW = 'DESTROYREQUEST_COMMENT_VIEW';
export const DESTROYREQUEST_COMMENT_ADD = 'DESTROYREQUEST_COMMENT_ADD';
export const DESTROYREQUEST_COMMENT_UPDATE = 'DESTROYREQUEST_COMMENT_UPDATE';
export const DESTROYREQUEST_COMMENT_DELETE = 'DESTROYREQUEST_COMMENT_DELETE';

//Loại lắp đặt
export const SHIPMENTSETUPTYPE_VIEW = 'SHIPMENTSETUPTYPE_VIEW';
export const SHIPMENTSETUPTYPE_ADD = 'SHIPMENTSETUPTYPE_ADD';
export const SHIPMENTSETUPTYPE_UPDATE = 'SHIPMENTSETUPTYPE_UPDATE';
export const SHIPMENTSETUPTYPE_DELETE = 'SHIPMENTSETUPTYPE_DELETE';

//Xem báo cáo vận đơn
export const SHIPMENTORDER_REPORT_VIEW = 'SHIPMENTORDER_REPORT_VIEW';

//Thưởng nhân viên
export const REWARD_VIEW = 'REWARD_VIEW';
export const REWARDDETAIL_VIEW = 'REWARDDETAIL_VIEW';

//Xem danh sách thưởng
export const TMS_TMSREWARD_VIEW = 'TMS_TMSREWARD_VIEW';

//Xem danh sách báo cao công nợ
export const TMS_BEGINTERMADVANCEDEBT_VIEW = 'TMS_BEGINTERMADVANCEDEBT_VIEW';