export const ERPCOMMONCACHE_SHIPMENTORDERSTEP = "ERPCOMMONCACHE.SHIPMENTORDERSTEP";
export const ERPCOMMONCACHE_PARTNER = "ERPCOMMONCACHE.PARTNER";
export const ERPCOMMONCACHE_PARTNERTYPE = "ERPCOMMONCACHE.PARTNERTYPE";
export const ERPCOMMONCACHE_CARRIERTYPE = "ERPCOMMONCACHE.CARRIERTYPE";
export const ERPCOMMONCACHE_SHIPMENTGOODSTYPE = "ERPCOMMONCACHE.SHIPMENTGOODSTYPE";
export const ERPCOMMONCACHE_SHIPMENTORDERSTATUS = "ERPCOMMONCACHE.SHIPMENTORDERSTATUS";
export const ERPCOMMONCACHE_SHIPMENTORDERTYPE = "ERPCOMMONCACHE.SHIPMENTORDERTYPE";
export const ERPCOMMONCACHE_FUNCTION = "ERPCOMMONCACHE.FUNCTION";
export const ERPCOMMONCACHE_USERGROUP = "ERPCOMMONCACHE.USERGROUP";
export const ERPCOMMONCACHE_SUBGROUP = "ERPCOMMONCACHE.SUBGROUP";
export const ERPCOMMONCACHE_SHIPMENTFEETYPE = "ERPCOMMONCACHE.SHIPMENTFEETYPE";
export const ERPCOMMONCACHE_COUNTRY = "ERPCOMMONCACHE.COUNTRY";
export const ERPCOMMONCACHE_PROVINCE = "ERPCOMMONCACHE.PROVINCE";
export const ERPCOMMONCACHE_DISTRICT = "ERPCOMMONCACHE.DISTRICT";
export const ERPCOMMONCACHE_WARD = "ERPCOMMONCACHE.WARD";
export const ERPCOMMONCACHE_PARTNERPRIVILEDGEGROUP = "ERPCOMMONCACHE.PARTNERPRIVILEDGEGROUP";
export const ERPCOMMONCACHE_STORE = "ERPCOMMONCACHE.STORE";
export const ERPCOMMONCACHE_SERVICETYPE = "ERPCOMMONCACHE.SERVICETYPE";
export const ERPCOMMONCACHE_SERVICESEASONTYPE = "ERPCOMMONCACHE.SERVICESEASONTYPE";
export const ERPCOMMONCACHE_SERVICEAGREEMENTTYPE = "ERPCOMMONCACHE.SERVICEAGREEMENTTYPE";
export const ERPCOMMONCACHE_IDDOCUMENTTYPE = "ERPCOMMONCACHE.IDDOCUMENTTYPE";
export const ERPCOMMONCACHE_TECHSPECS = "ERPCOMMONCACHE.TECHSPECS";
export const ERPCOMMONCACHE_TECHSPECSVALUE = "ERPCOMMONCACHE.TECHSPECSVALUE";
export const ERPCOMMONCACHE_MAINGROUP = "ERPCOMMONCACHE.MAINGROUP";
export const ERPCOMMONCACHE_SUBGROUPTECHSPECS = "ERPCOMMONCACHE.SUBGROUPTECHSPECS";
export const ERPUSERCACHE_FUNCTION = "ERPUSERCACHE.FUNCTION";
export const ERPCOMMONCACHE_SKILLCATEGORY = "ERPCOMMONCACHE.SKILLCATEGORY";
export const ERPCOMMONCACHE_SKILLRANK = "ERPCOMMONCACHE.SKILLRANK";
export const ERPCOMMONCACHE_AREATYPE = "ERPCOMMONCACHE.AREATYPE";
export const ERPCOMMONCACHE_BRAND_MAINGROUP = "ERPCOMMONCACHE.BRAND_MAINGROUP";
export const ERPCOMMONCACHE_BRAND = "ERPCOMMONCACHE.BRAND";
export const ERPCOMMONCACHE_AREA = "ERPCOMMONCACHE.AREA";
export const ERPCOMMONCACHE_INSTALLBUNDLE = "ERPCOMMONCACHE.INSTALLBUNDLE";
export const ERPCOMMONCACHE_STORE_AREA = "ERPCOMMONCACHE.STORE_AREA";

export const ERPCOMMONCACHE_WORKINGSHIFT = "ERPCOMMONCACHE.WORKINGSHIFT";
export const ERPCOMMONCACHE_LIMITTYPE = "ERPCOMMONCACHE.LIMITTYPE";

export const ERPCOMMONCACHE_DES_RVLEVEL = "ERPCOMMONCACHE.DES_RVLEVEL";
export const ERPCOMMONCACHE_INV_RVLEVEL = "ERPCOMMONCACHE.INV_RVLEVEL";
export const ERPCOMMONCACHE_TMS_SERVICETYPE = "ERPCOMMONCACHE.TMS_SERVICETYPE";
export const ERPCOMMONCACHE_AREATT = "ERPCOMMONCACHE.AREATT";






